### PR TITLE
Tests & encoding fixing

### PR DESCRIPTION
**Pull request by ThmsLa**
Python 2 encoding issues are a living hell. Tried to do the best out of it, and it works well! 🙃
Thanks @ebreton for detecting these issues again!

& bumped the version number

### CODE REVIEW

**Comment by ebreton** [comment]
@ThmsLa  you are more than welcome !

My pull request was pending in the air and started to rot a bit (some conflicts emerged). I therefore merged it, and that generated some conflicts in your branch which I also try to resolve.

Some tests are failing (among them mapzen which we has nothing to do with your PR)... I will have a look at it tomorrow. Bedtime here :)

**Comment by ebreton** [comment]
Hi @ThmsLa , 

Please look at #343 for a few suggestions on refactoring (you have address somethings in your PR already). 

Withor without my suggestions, the objective is to make the bing tests pass :sunglasses:

**Comment by ThmsLa** [comment]
Thanks @ebreton! 
Sorry I messed up your tests with my old commits. Bing tests are now running fine.

The MapQuest test failing seems to be linked to some strange API key error. MapZen's have an SSL error, I guess we can't do much about it.

**Comment by ThmsLa** [comment]
Regarding the MapQuest test, it seems linked to paid API keys having errors issues sometimes: https://developer.mapquest.com/forum/paid-key-intermittent-403-error-not-valid-key

**Comment by DenisCarriere** [comment]
@ThmsLa Not too sure if this PR is relevant anymore?

**Comment by ThmsLa** [comment]
@DenisCarriere I'll check next Monday, but a few things might be relevant, especially regarding the tests. Thanks for the invitation btw! :)

**Comment by ThmsLa** [comment]
@ebreton @DenisCarriere Since MapZen is shutting down, I marked the MapZen class as deprecated and updated the tests accordingly. 
Seems better than removing all the MapZen related files, as users using it will get a relevant exception from it. If you're fine with it I'll merge :)

**Comment by DenisCarriere** [comment]
👍 Nice! Agreed, we can keep Mapzen but define it as deprecated 😢

Amazing, the first PR that has passing tests ✅ 🚀

**Pull request merged**
