### PR TITLE
Add pep8 scanning to CI job

### PR DESCRIPTION
**Pull request by zxiiro**
This patch enables Travis CI to automatically scan for pep8 violations and report back in the build. Uses flake8 to perform this task.

One exception to the pep8 default rules is we allow 120 max line length instead of the default 79 characters.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Everything looks great, however there's just the __init__.py file that shouldn't change, there's a reason why all those imports are there. It enables a simple simple `import geocoder` then right into the functions.

Try your code and it will break.

```python
import geocoder
g = geocoder.google("Ottawa")
```

**Comment by DenisCarriere** [comment]
Yea I should do some Pep8 testing with Flake, I've heard about it before, just never enabled it. I've got Pytest goiyadng on and Tox, all this stuff is brand new to me this year. I'm getting better though ;) Day by day!

**Comment by DenisCarriere** [comment]
I added back the imports in the init file with the noqa comments for Flake8, cool stuff for testing purposes

**Comment by zxiiro** [comment]
Huh, I didn't remove the imports though. All I did was moved it to the top. "noqa" tells flake8 to ignore the pep8 violations.

**Comment by zxiiro** [comment]
Strange. Oh well.

**Comment by DenisCarriere** [comment]
No they were removed.. lol! You must of done two commits, the first commit was the "noqa" comments, then the 2nd commit was to remove them... No worries, I added them back

**Comment by DenisCarriere** [comment]
Now the code runs Flake8 no issues! Looks good!

**Comment by DenisCarriere** [comment]
Thanks for adding that in! I'll continue to work on this code, it seems to have a lot of people interested

**Comment by zxiiro** [comment]
No problem. I like helping people get CI configured.

**Comment by DenisCarriere** [comment]
Yea, once it's set up it's really good for troubleshooting when you make silly mistakes

**Pull request merged**
