### PR TITLE
Start refactoring to handle mutiple results

### PR DESCRIPTION
**Pull request by ebreton**
Hi @DenisCarriere 

I gave a shot for the multiple result support...  worked mainly in **base.py**
- and adapted the **geonames.py** provider consequently.
- Also adapted the **test_geonames.py** to keep them passing, and check that we actually have multiple results

The main change is the splitting of the `Base` class between 
- one for a result, `OneResult`
- and one for the management of the query, `MultipleResultsQuery`

The second, to manage the query, is an [ordered set](http://orderedset.readthedocs.io/en/latest/). It allows us to store directly the results, to keep their order, and to benefit from all the features from a set (and a bit more), like: iteration, pop, index, ...

Refactoring within a provider roughly goes through two steps (example taken with geonames):
- creating a child for one result : `GeonamesResult`, responsible for the parsing at the locations level
- overriding the query manager: `GeonamesQuery`, responsible for the parsing at the highest level, e.g error and getting the array of location objects

Let me know what you think. We will certainly refine when refactoring other providers

### CODE REVIEW

**Comment by ebreton** [comment]
I left aside how to access the results. I think you need to lead on this one.

For now, the api makes use of the QueryManagers, which allow access to the results via `iterators`or `pop` or `index`. But **not** directly. Thats is a breaking change.

Two examples to make my point more clear. from test_geonames.py:

**query on one point, with pop (could be g[0] also):**

```
        g = geocoder.geonames(location)
        assert g.ok
        assert repr(g) == '<[OK] Geonames - Geocode [Ottawa]>'
        assert len(g) == 1
        assert g.status_code == 200
        assert g.url == 'http://api.geonames.org/searchJSON?q=Ottawa%2C+Ontario&fuzzy=0.8&username=mock&maxRows=1'

        point = g.pop()
        assert point.ok
        assert point.geonames_id == 6094817
        assert point.lat == '45.41117'
        assert point.lng == '-75.69812'
        ....
```

**query on several point, with iterator:**

```
        g = geocoder.geonames(6094817, method='children')
        assert g.ok
        assert repr(g) == '<[OK] Geonames - Children #2 results>'
        assert len(g) == 2
        assert g.status_code == 200
        assert g.url == url

        expected_names = ["Birch Manor", "Templeton-Est"]
        expected_geonames_id = [5901584, 6162703]
        assert expected_names == [res.address for res in g]
        assert expected_geonames_id == [res.geonames_id for res in g]
        ....
```

**Comment by DenisCarriere** [comment]
@ebreton Thanks a lot for your contributions, however I think handling the multiple results (even all results) should be stored as GeoJSON Point FeatureCollection.

http://geojson.org/

- [ ] All providers should return a FeatureCollection regardless if it's 1 result or multiple results.
- [ ] Custom properties from providers should be stored in each individual GeoJSON Point `properties`.

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          39.7265625,
          35.17380831799959
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          21.09375,
          54.57206165565852
        ]
      }
    }
  ]
}
```

This change is massive, hence why I never tackled it 🤓 , it might be better to do a full re-write of the entire library.

**Comment by ebreton** [comment]
Agreed to provide GeoJSON FeatureCollection. Makes a lot of sense.

However, I would not force the storage to be in geojson. The way you do it in the current lib is more flexible, and geojson is provided on the top with the properties.

Hence you will find the code adapted to provide a `geojson` property on the highest level (query manager). That answers the use case without rewriting everything 👍 

Following my idea of "pointer", I have also reviewed a bit the query manager to forward calls to a `current_result`. We keep full backward compatibility this way... which is kind of verrryyy nice ;)

An new method `expose_result(index)` will allow the user to change the current_result and access any particular other one (if iterating or geojson are not sufficient)

**Comment by DenisCarriere** [comment]
> Following my idea of "pointer", I have also reviewed a bit the query manager to forward calls to a current_result. We keep full backward compatibility this way... which is kind of verrryyy nice 

Sweet! Looking forward to it!

> Hence you will find the code adapted to provide a geojson property on the highest level (query manager). That answers the use case without rewriting everything 👍

Agreed, using the `geojson` property is good enough, we could however make the `geojson` as a FeatureCollection instead of a single Feature, thoughts?

**Pull request merged**
