### PR TITLE
Added developer key functionality for Baidu

### PR DESCRIPTION
**Pull request by avanderm**
Added signature creation for Baidu documented [here](http://lbsyun.baidu.com/index.php?title=lbscloud/api/appendix). Some things to note:

- in the case of Chinese characters, do not include the address in the `urlencode` function when computing the signature, or the API call will fail
- replace commas and spaces in addresses with the `%` symbol to make sure the signature matches the one computed on the Baidu site

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@avanderm 👍 Looks good to me! Thanks for the PR

@ebreton Strange the tests are still not passing, the errors are related to ArcGIS & Google providers... 🤔

**Comment by DenisCarriere** [comment]
Anyway we could make the tests pass before I merge... I know this PR isn't related to ArcGIS or Google, but I wouldn't want to have a constant failing master branch.

**Comment by avanderm** [comment]
Noticed that too. Now that I think of it, I need to update the documentation for Baidu if this passes.

**Comment by DenisCarriere** [comment]
@avanderm 👍 I'm going to merge this now, since this PR has ZERO relevance with the current errors, we can look at those errors later.

Once the master branch passes I'll push a new minor release.

**Pull request merged**
