### PR TITLE
getting a sense of the lib: enriching a bit geonames

### PR DESCRIPTION
**Pull request by ebreton**
- added a test file for geonames
- retrieved more attributes from results
- added methods children and hierarchy
- reviewed slightly doc

question : how should be handled multiple results (e.g. the ones from hierarchy) ?

### CODE REVIEW

**Comment by ebreton** [comment]
I guess #59 gives an answer to my question... ?
If yes, we can discuss there ^^

**Comment by ebreton** [comment]
Thanks for the invite ! 
Write accesses ok. 

Are you confortable to work within an open pull request for new features ?

We could use feature_multi_result to discuss #59 for instance

**Comment by ebreton** [comment]
I did not see before, but the build fails from master...
strange since it works from the PR...
Have you investigated already ?

**Comment by DenisCarriere** [comment]
It is strange that the master branch fails but the PR passes.

Would be better if the tests didn't have to make HTTP requests instead the tests should simply parse JSON responses.

**Comment by DenisCarriere** [comment]
@ebreton Let me know whenever you want me to push a new release on PyPi, just `@` me with the release version.

**Comment by ebreton** [comment]
would it be only for me, I would push every merge that is done on master. Ideally, with a successful build of course... but if you latest releases were made with the same states, I would go for keeping the releases ongoing.

How much automated is your release process to PyPi ?

With regards to the the http requests in tests, I agree with you, definitively. A quick look for mocking  requests leads to : http://requests-mock.readthedocs.io/en/latest/index.html

I am going to give a try for this

**Comment by DenisCarriere** [comment]
👍 using mocking requests.

Just recently I've had to entirely redo PyPi process, I think it got simpler, but I'm 👍 doing an entire revamp to make it simpler. In the ideal world it would be nice to publish a new release directly from TravisCI (if the version changes).

I've been in the NPM ecosystem for a while and I find publishing Python modules to be quite a pain, however with the new PyPi it got a tad easier.

**Comment by ebreton** [comment]
> I'm 👍 doing an entire revamp to make it simpler. 

cool. I am interested ! 
is it on github ?

**Comment by DenisCarriere** [comment]
No I said "I'm good if we do an entire revamp" which is what you are currently doing 👍

**Comment by ebreton** [comment]
aaah ok :) 

sooo... how do you currently push to pipy ? Makefile ?

**Comment by DenisCarriere** [comment]
I have a Makefile, however PyPi changed and I don't know if the Makefile is correct anymore.

I only published once using the new PyPi, still new to it.

**Pull request merged**
