### PR TITLE
Google reverse fix

### PR DESCRIPTION
**Pull request by MRigal**
At least fixing the failing test due to to PR #237 maybe finally fixing #236
(I have also no client to debug it)

### CODE REVIEW

**Comment by MRigal** [comment]
@DenisCarriere please review :)

**Comment by DenisCarriere** [comment]
@MRigal 👍 Sweet looks good! I'll add you as a contributor to this project.

**Comment by MRigal** [comment]
Thanks @DenisCarriere !
I'm fine in becoming a contributor and I could review some things with pleasure, but don't expect neither too much commitment from my side, it will probably stay limited...

Besides that, you may have a look at this: https://github.com/orderbird/geocoder/pull/1/files

Aiohttp support is actually mostly working (and speeding up dramatically!!!), but as it requires so much changes (including I plan to drop support for Python < 3.5), it might rather be a separate project... But maybe I can discuss that with you now :-p Feel free to open any discussion space for that topic

**Comment by DenisCarriere** [comment]
👍 Sounds good, sadly I don't have much time to contribute to the `geocoder` library, however I'm willing to give 100% permissions to any contributors & `pypi` publishing to anyone who wants to maintain it.

Feel free to drop Python2 support (we're in 2017... people should be using Python3 by now).

**Comment by DenisCarriere** [comment]
I have a Javascript/NodeJS equivalent [`geocoder-geojson`](https://github.com/DenisCarriere/geocoder-geojson), it's not as complete as the Python one, but it's a full re-write and focused on outputting GeoJSON.

**Pull request merged**
