### PR TITLE
Feature bbox for geonames

### PR DESCRIPTION
**Pull request by ebreton**
- support bbox parameter when geocoding with proximity
- support bbox property when using method details

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks, however this is the Leaflet/Google bbox format and not the GeoJSON `bbox` format.

We could easily support, the GeoJSON bbox is Array of 4 numbers `[west, south, east, north]` => `[-76.353915, 44.962733, -75.2465979, 45.5375801]`.

https://github.com/DenisCarriere/geocoder/blob/master/geocoder/base.py#L325

**Comment by ebreton** [comment]
interesting. Yes that would be trivial to support both.

Before I do it, would you be ok to add a page in the doc about bbox format ? 

- the differences that exist (between google format and geojson to start with)
- and more important: how geocoder is supposed to handle 

My idea is to provide the user with the description of a consistent experience (i.e how you want geocoder to handle all this).

I will push a commit adapting to your description ;)

**Comment by DenisCarriere** [comment]
:) Very trivial I know... Maybe we can rename the `northeast` & `southwest` as `bounds` instead of `bbox`.

So the `bounds` (northeast, southwest) formats derives from Google Maps (Leaflet uses that as well).
https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLngBounds

And the GeoJSON spec uses `bbox`, so maybe making a difference between both.

I'll look into adding this to the docs before we move ahead.

**Comment by ebreton** [comment]
sounds good 👍

**Pull request merged**
