### PR TITLE
TGOS provider

### PR DESCRIPTION
**Pull request by virus-warnning**
* TGOS provider
* requirements

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks for the PR, but can you add the following:
- Tests
- PEP8 compatible syntax
- Add provider to documentation
- Is beautiful soup really necessary?

**Comment by virus-warnning** [comment]
Beautiful soup is used to obtain a variable in Javascript.

**Comment by virus-warnning** [comment]
I'll improve doc later, thanks for your suggestion.

**Comment by DenisCarriere** [comment]
Thanks for the PR, tests are passing, thanks for your contributions. 👍

**Comment by virus-warnning** [comment]
I'll improve the doc in next PR. Thanks for your merging.

**Comment by DenisCarriere** [comment]
@virus-warnning I'm looking at the official TGOS maps API and it's a nightmare! I'm glad you made this PR because I wouldn't of known where to start with this one. Good job again!

**Comment by DenisCarriere** [comment]
@virus-warnning I'm going to clean the TGOS provider when I fully understand how it works, I don't think we will need to use PyProj or BeatifulSoup.

Here's an URL API call I just made to receive JSON.

[http://gis.tgos.nat.gov.tw/TGLocator/TGLocator.ashx?format=json&{...}](http://gis.tgos.nat.gov.tw/TGLocator/TGLocator.ashx?format=json&input=%E5%8F%B0%E5%8C%97%E5%B8%82%E5%85%A7%E6%B9%96%E5%8D%80%E5%85%A7%E6%B9%96%E8%B7%AF%E4%B8%80%E6%AE%B5735%E8%99%9F&srs=EPSG:4326&ignoreGeometry=false&pnum=1&center=120.84350081380833,23.149869272721165&jsonp=TGOS.getJSON%5B%27sn3%27%5D)

**Pull request merged**
