### PR TITLE
Use requests sessions

### PR DESCRIPTION
**Pull request by MRigal**
Addressing issue/enhancement proposal https://github.com/DenisCarriere/geocoder/issues/220

Here is a proposal

### CODE REVIEW

**Comment by MRigal** [comment]
OK, I have to fix the CLI.

I guess the census failure is more a systematic one...

**Comment by DenisCarriere** [comment]
@MRigal Overall looks good to merge, if you could fix that CLI issue and comment out the `uscensus` provider since it always fails.

https://github.com/DenisCarriere/geocoder/blob/master/tests/test_geocoder.py#L272-L275

**Comment by MRigal** [comment]
Fixed.

Also using @pytest.mark.xfail(raises=TimeoutError) to xpass the baidu and uscensus tests if we have a timeout error and failing for other reasons, better than commenting out!

The coverage decreased because it was erroneously measured before. In the opposite, it raised for the base class

**Comment by DenisCarriere** [comment]
@MRigal Perfect, thanks a lot for taking the time to send this PR.

Cheers,

**Comment by MRigal** [comment]
You're welcome!
Thanks for the fast new release also :-)

**Pull request merged**
