### PR TITLE
Tamu provider support

### PR DESCRIPTION
**Pull request by ac6y**
Hi Denis,
We added a module to support Tamu (Texas A&M University GeoServices), as they make some census data available that we needed, which seems hard to find in other services.  Unfortunately Tamu's api doesn't seem to accept a single string for the location, instead requiring a tuple of (address, city, state, zipcode).  I hope the way this was handled, as additional required named params, seems appropriate.

There are still some things we would like to add to tamu.py module, in order to expose some more of Tamu's API, but thought we'd pass along the code in the meantime anyway.

Thanks for making this great geocoder package available!  It's been extremely helpful.  Hope you might find the Tamu addition to be useful.

Cheers,
Michael

### CODE REVIEW

**Comment by ac6y** [comment]
I wasn't sure how to add an env variable for the Travis CI build - sorry!  So right now a demo API key is being passed for the test calls in these 2 locations:

[tests/test_geocoder.py line 247](https://github.com/ac6y/geocoder/blob/master/tests/test_geocoder.py#L247)

[geocoder/tamu.py line 232]
(https://github.com/ac6y/geocoder/blob/master/geocoder/tamu.py#L232)

The key param can be removed if the tamu_key is set in the env:

`TAMU_API_KEY=demo`

**Comment by ac6y** [comment]
The tTrests are currently failing because the freegeoip.net service is apparently unresponsive.

The following URL times out often, (but not always), even with a timeout of 10 seconds, as of 2016-03-24 02:59 UTC:

[http://freegeoip.net/json/99.240.181.199](http://freegeoip.net/json/99.240.181.199)

**Comment by DenisCarriere** [comment]
Thanks Michael for this extra module! I'll have a look at it tomorrow and make sure the build is working in Python3, I'll look at Tamu's API and see if I can improve it in my Geocoder

**Comment by ac6y** [comment]
Wonderful!  :)
Really enjoying using your Geocoder package - thanks again.
-M

**Comment by DenisCarriere** [comment]
@ac6y I added the Tamu key in the Travis build, I'm the only one that can edit those :+1: 

I've also noticed that FreeGeoIP isn't very  stable as a server, I'll remove it from the testing but what's great with that one is you can host it locally.

Cheers!

**Comment by ac6y** [comment]
@DenisCarriere Thanks Denis, makes sense.

And definitely great that FreeGeoIP is open source... it sounds like the public service may actually be shutting down...  https://github.com/fiorix/freegeoip/issues/165

**Pull request merged**
