### PR TITLE
Added LocationIQ provider.

### PR DESCRIPTION
**Pull request by theju**
Refs #235

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@theju Thanks for the PR, however the tests are failing and they are related to this PR.

https://travis-ci.org/DenisCarriere/geocoder/jobs/284149169#L679

**Comment by theju** [comment]
Providing the key as an environment variable will fix it. How do you suggest I go about this?
I don't want to complicate the setup by using encrypted environment variables as documented in Travis.
https://docs.travis-ci.com/user/environment-variables/

**Comment by ebreton** [comment]
I would say that the simplest option is to mock the request. That will allow to put any key and still have the test passing.

You can find examples in test_geocodefarms.py :)

**Comment by theju** [comment]
@ebreton I updated the tests by mocking the results but got an unrelated error in different providers. I guess Travis was having some network issues?

One of the error is:
```
<[ERROR - HTTPSConnectionPool(host='photon.komoot.de', port=443): Read timed out. (read timeout=5.0)] Komoot - Reverse [empty]>.ok
```

**Comment by DenisCarriere** [comment]
Strange.. seems like the PR did work:

image

**Comment by ebreton** [comment]
timeouts... that occurs (unfortunately) quite often...

What I usually do is set a timeout of 10 sec on the providers that have an error (default is 5)

I will do the same again

**Pull request merged**
