### PR TITLE
Add support for Google Places API for 'ambiguous' geocoding

### PR DESCRIPTION
**Pull request by cspinelive**
Adding an option for geocoding phrases that are not pristine formatted addresses such as 'white house', '1st and main', 'Walmart, Tulsa, OK', etc.

https://developers.google.com/maps/documentation/geocoding/best-practices
https://developers.google.com/places/web-service/intro

### CODE REVIEW

**Comment by cspinelive** [comment]
I see api.py failed the pep8 check.  Let me know how I can correct this if I need to.

**Comment by cspinelive** [comment]
The tests failed because the api key doesn't have access to the Places API.  It was using the API key found in your environment variables.  You might need to go to the Google Developers Console and enable this API: https://console.developers.google.com/apis

Please advise.

{
    "status": "REQUEST_DENIED", 
    "error_message": "This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_", 
    "location": {}, 
    "html_attributions": [], 
    "results": []
}

**Comment by DenisCarriere** [comment]
Awesome @cspinelive Thanks!
Looks great, I don't see any issues with the PR.
I'll bump the version for PyPi

**Comment by DenisCarriere** [comment]
Ok Build passing & bumped PyPi version to 1.8.0
https://travis-ci.org/DenisCarriere/geocoder

**Pull request merged**
