### PR TITLE
add baidu reverse

### PR DESCRIPTION
**Pull request by xiangmeng4geo**

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks, however when adding a new method to a provider, you will also need to include the method in the [`geocoder/api.py`](https://github.com/DenisCarriere/geocoder/blob/master/geocoder/api.py) file as well.

And also add tests to make sure it works, you can use [`tests/test_opencage.py`](https://github.com/DenisCarriere/geocoder/blob/master/tests/test_opencage.py) as a simple example.

**Comment by xiangmeng4geo** [comment]
OK，I will commit new PR latter.

**Comment by DenisCarriere** [comment]
You could've kept this PR opened and sent commits to this branch at a later time.

**Comment by xiangmeng4geo** [comment]
Adding a new method to a provider,and include the method in the geocoder/api.py file.

**Comment by DenisCarriere** [comment]
👍 @xiangmeng4geo Thanks a lot for adding the new provider `Gaode` as well

**Comment by DenisCarriere** [comment]
Published under new release under `v1.28.0`

**Comment by ebreton** [comment]
Hello @xiangmeng4geo !

What about adapting the code to support multiple results for Baidu and Gaode ?

It basically comes to split your existing classes in two: 

```
# from geocoder.base import Base
#
# becomes

from geocoder.base import OneResult, MultipleResultsQuery
```

- one for to handle the results and all their properties (where the JSON moved from `self.parse` to `self.raw`:

```
class MapquestResult(OneResult):

    @property
    def lat(self):
        return self.raw['latLng'].get('lat')

    @property
    def lng(self):
        return self.raw['latLng'].get('lng')

...
```
- and one to handle the query. 

```
class MapquestQuery(MultipleResultsQuery):
    provider = 'mapquest'
    method = 'geocode'

    _URL = 'http://www.mapquestapi.com/geocoding/v1/address'
    _RESULT_CLASS = MapquestResult
    _KEY = mapquest_key

    def _build_headers(self, provider_key, **kwargs):
        ...


    def _build_params(self, location, provider_key, **kwargs):
        ...


    def _catch_errors(self, json_response):
        ...


    def _adapt_results(self, json_content):
        ...

```



You may want to have a look on the providers already "migrated", like geonames, bing, mapbox or mapquest.

**Comment by DenisCarriere** [comment]
👍

**Comment by xiangmeng4geo** [comment]
OK, I will try it at weekend.

**Comment by xiangmeng4geo** [comment]
Hello,@ebreton
I've just checked the API of Gaode and Baidu, and their geocoding service only supports a return 
 one result, so I might not be able to do support multiple results for Baidu and Gaode.

**Comment by ebreton** [comment]
ok, the exercice is less interesting then :(

If you can adapt the code to make use of the new structure, that still has some value. If not, just tell me and I will take it from here.

Cheers,
Manu

**Comment by xiangmeng4geo** [comment]
I'm sorry about that too. So I will try to provide implement for both of them by new structure.

**Comment by ebreton** [comment]
Hi @xiangmeng4geo , 

I would like to close the refactoring session. I will therefore update the code for Baidu and Gaode in PR #288 . Once in place, do not hesitate to make any comments !

**Comment by xiangmeng4geo** [comment]
Sorry ,my English is poor.
Did you mean you will refactor Baidu and Gaode by new structure?

**Comment by ebreton** [comment]
Yes, I will do it right away :)

I just have some problems to get a Gaode API key... looks complicated from Europe.

So, I think I will just do what I can without the API and ask you to test

**Comment by ebreton** [comment]
Actually, could you create a Gaode API key that we could use for tests ?

**Comment by xiangmeng4geo** [comment]
I can provide a api key for test .
key='0716e5809437f14e3dd0793a5c6d2b13'

**Comment by xiangmeng4geo** [comment]
By the way, gaode only provide geocode in Chinese location.So I can test the code if you need.

**Comment by ebreton** [comment]
Refactored done and pushed to branch `feature_more_providers_upgraded`
Looks ok for me (tests are passing)

Could you check on your side that everything works as before ?
I will then ask Denis to merge 👍

**Comment by xiangmeng4geo** [comment]
@ebreton baidu and gaode works fine too 👍 .
And I commit a PR #289  to  **feature_more_providers_upgraded**  to empty the test key .

**Pull request merged**
