### PR TITLE
finalized refactoring

### PR DESCRIPTION
**Pull request by ebreton**
Added Changelog at the end of README (mention coverages in those)

Upgraded following providers 

- yandex
- tomtom (making use of new API)
- ottawa
- canadapost
- mapzen

### CODE REVIEW

**Comment by ebreton** [comment]
Hi @DenisCarriere !

I have done a bit of "packaging" work on the [README in this branch](https://github.com/DenisCarriere/geocoder/blob/feature_more_providers_upgraded/README.md). Could you have a look at it and tell me what you think ?

**Comment by ebreton** [comment]
I also welcome feedback on the [Changelog](https://github.com/DenisCarriere/geocoder/blob/feature_more_providers_upgraded/CHANGELOG.md) :)

**Comment by DenisCarriere** [comment]
👍 @ebreton Love it! I really like the new centered README doc.

image

> As a side note: Not sure how it will behave on pipy...

I wouldn't be too worried about that 😄, but we will see when we publish the next release.

> I also welcome feedback on the Changelog :)

I like it! Lots of details is better than no details

**Comment by DenisCarriere** [comment]
Just published to [`PyPi`](https://pypi.org/project/geocoder/) & [`snapcraft.io`](https://build.snapcraft.io/user/DenisCarriere/geocoder).

@ebreton Doesn't look like PyPi liked the Markdown, but I like it on GitHub so keep it the way it is... that's PyPi's fault to not render it properly.

**Pull request merged**
