### PR TITLE
Snaps packaging

### PR DESCRIPTION
**Pull request by tian2992**
A first version to create a snap package.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@tian2992 Thanks for the PR, however what's a snap package? and how would this be used? Can you elaborate more on the purpose of snap packages (I must be out of the loop on this topic).

**Comment by elopio** [comment]
Hello @DenisCarriere! Snapcraft is a new packaging format for all Linux distros, that we are developing in Ubuntu. You can read more here: https://snapcraft.io/

Once the snapcraft.yaml is in your master branch, you can just go to https://build.snapcraft.io to automate the continuous delivery of updates to the Ubuntu store.

**Comment by elopio** [comment]
\o/ thanks for the merge @DenisCarriere. 

@tian2992 did this as part of a workshop during a Central American free software conference. Nice work, thanks to you too!

The geocoder name is now registered in the store under @tian2992, which was an exercise we did to learn about publishing. But if you want to start publishing geocoder under your official name, I can make the transfer. @DenisCarriere you just need to fill this form, explaining that you are the original author: https://dashboard.snapcraft.io/dev/snaps/register-name/

pura vida

**Comment by tian2992** [comment]
Cheers! Thanks for accepting the PR!

**Comment by DenisCarriere** [comment]
👍 Yes if we could transfer the repo that would be great.

**Comment by elopio** [comment]
Just let me know when you are done with the form, and I can click the button.

**Comment by DenisCarriere** [comment]
Ok, ready whenever you are.
image

**Comment by DenisCarriere** [comment]
image

**Comment by elopio** [comment]
Done. Please let us know if you have any issues with build.snapcraft.io. 
And once you have the snap in the edge channel, we can make a call for testing with the Ubuntu community to get more people trying it before making the first stable release.

**Comment by DenisCarriere** [comment]
👍

**Comment by DenisCarriere** [comment]
So these snap packages are mostly for CLI based applications, correct?

**Comment by elopio** [comment]
No, there are also GUI snaps. For example, try:

`sudo snap install keepassxc`

But it is not for libraries. After installing the geocoder snap, only the CLI script can be executed, it can't be imported from a python terminal. It's like we have virtualenv for development, and snaps for deployment.

For your side right now, it only remains to suggest to your early adopters and contributors to give it a try with:

`sudo snap install geocoder --edge`

Then, when you are happy with the quality of a version and want to make it visible on user searches, you just run:

`snapcraft release geocoder <revision> stable`

**Comment by DenisCarriere** [comment]
Doesn't seem to recognize the `geocode` CLI...?

Does it work for you?

```bash
$ snap install geocoder --edge --devmode 
geocoder (edge) 1.23.2 from 'deniscarriere' installed
$ geocode
zsh: command not found: geocode
```

**Comment by elopio** [comment]
The name of the command chosen by Sebastián is `geocoder`.

The name of the command is a combination of rules between the `name` and `apps` fields in the snapcraft.yaml. If you want the command to be `geocode`, you would have to rename the snap to `geocode`, or use an [alias](https://forum.snapcraft.io/t/improving-the-aliases-implementation/18/32).

**Comment by DenisCarriere** [comment]
Perfect, thanks, it somewhat works now:

Going to switch it back to Python2 and 🤞 it should work.

This is pretty slick! I'll continue to maintain these builds for future releases and other projects.
```
$ snap run geocoder "Ottawa, ON"
Traceback (most recent call last):
  File "/snap/geocoder/5/bin/geocode", line 11, in <module>
    sys.exit(cli())
  File "/snap/geocoder/5/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/geocoder/5/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/snap/geocoder/5/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

Click discovered that you exported a UTF-8 locale
but the locale system could not pick up from it because
it does not exist.  The exported locale is "en_US.UTF-8" but it
is not supported
```

**Comment by elopio** [comment]
@DenisCarriere you can make sure that the right encoding is before executing the `command` binary.

Something like this:

`command: env LC_ALL=C.UTF-8 LANG=C.UTF-8 bin/geocode`

**Comment by DenisCarriere** [comment]
👍

**Pull request merged**
