### PR TITLE
Provide gisgraphy geocoder

### PR DESCRIPTION
**Pull request by hbruch**
David Masclet currently prepares gisgraphy geocoder V5. This PR provides a client implementation. 
API key policy still / test case handling needs to be clarified.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@hbruch Thanks for the PR, however your current PR seems to fail in the Travis CI test.

Read the error listed below:
https://travis-ci.org/DenisCarriere/geocoder/jobs/331686394#L704-L734

Once the tests pass we can merge this new provider.

🎉

**Comment by hbruch** [comment]
@DenisCarriere  Thanks for pointing me to this. Tests are now fixed.

**Comment by DenisCarriere** [comment]
👍 @hbruch Awesome, i'll push these changes to a minor release.

**Comment by gisgraphy** [comment]
@hbruch Is it possible to update the readme file to put Gisgraphy as a provider ?

**Comment by DenisCarriere** [comment]
@gisgraphy feel free to send a PR with the appropriate changes.

**Comment by kbrose** [comment]
@gisgraphy this now returns a 401 error:

```
>>> import geocoder
>>> geocoder.gisgraphy('100 S. State Street, Chicago Illinois')
Status code 401 from https://services.gisgraphy.com/geocoding/: ERROR - 401 Client Error: Unauthorized for url: https://services.gisgraphy.com/geocoding/?address=100+S.+State+Street%2C+Chicago+Illinois&limitnbresult=1&format=json
<[ERROR - 401 Client Error: Unauthorized for url: https://services.gisgraphy.com/geocoding/?address=100+S.+State+Street%2C+Chicago+Illinois&limitnbresult=1&format=json] Gisgraphy - Geocode [empty]>
```

When I copy the URL into a browser it works fine.

**Comment by gisgraphy** [comment]
This pull request should fix it : https://github.com/DenisCarriere/geocoder/pull/348

**Pull request merged**
