### PR TITLE
Add the instructions to install the snap

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks @elopio 👍

**Comment by DenisCarriere** [comment]
So would I need to publish new releases? Or `--edge` would just mean it's using the latest version?

Still a bit unsure about how to publish an official release

**Comment by elopio** [comment]
Thanks for the merge @DenisCarriere !
Every time your master branch changes, build.snapcraft.io will build a new snap and release it to the edge channel.

To simplify the packaging tasks, I prefer to use [git annotated tags](https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags) (which is a good practice anyway IMO). With that, you can set `version: git` in the snapcraft.yaml. And the next time you make a release tag in github, that version will land properly identified in edge. If you want that version to be visible on user searches, and to go to all your stable users, you use the `snapcraft release` to put it in the stable channel.

We hang in https://rocket.ubuntu.com and https://forum.snapcraft.io, in case you have more questions or need a hand with something.

pura vida.

**Comment by DenisCarriere** [comment]
@elopio Sweet I just published the latest release `v1.25.0` to the stable channel.

Feel free to send over any documentation on how to use it.

```
$ snap find geocoder
Name      Version  Developer      Notes  Summary
geocoder  1.25.0   deniscarriere  -      Geocoder is a simple and consistent geocoding library.
```

**Comment by DenisCarriere** [comment]
👍 Perfect stuff! As long as you keep making sure the docs are updated I'm good with that 👍 

This was quite useful 😄 
https://snapcraft.io/docs/build-snaps/publish

**Comment by elopio** [comment]
:D I've just proposed #268.

**Comment by DenisCarriere** [comment]
❤️ Awesome, thanks! Have a good night (or day)

**Pull request merged**
