### PR TITLE
Fix the Opencage error and add all of the other Opencage Aliases

### PR DESCRIPTION
**Pull request by nyejon**
Hi Denis,

I have created this to address issue: #276 and add additional functionality.

Added all of the aliases as defined in: https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml

Fixed the circular city lookup error and created a more robust lookup for the aliases if one does not exist.

Updated tests to include country and country_code

### CODE REVIEW

**Comment by ebreton** [comment]
Hi @nyejon !

Thanks for the fix and the upgrade 👍 

Would you agree to also make the change on the code to support multiple results ? 

It basically comes to split your class in two: one for to handle the results and one to handle the query. You may want to have a look on the providers already "migrated", like geonames, bing, mapbox or mapquest.

I would appreciate a lot your feedback on this !
Manu

**Comment by nyejon** [comment]
Hi Manu

Yes, I can give it a go to get the multiple results working. It would be useful to have this change merged in the meantime as currently the opencage geocoder doesn't work at all as of the current release.

**Comment by DenisCarriere** [comment]
👍 @nyejon Great work, sorry for the delayed merge.

**Comment by DenisCarriere** [comment]
@nyejon Just published a new release with your changes `v1.29.0`

**Comment by nyejon** [comment]
@DenisCarriere fantastic, thanks a lot!

**Comment by nyejon** [comment]
@DenisCarriere I have installed the 1.29 version and it still contains the old opencage.py for some reason.

**Comment by DenisCarriere** [comment]
Ops, I was on a different branch when I publish 🤦‍♂️ Thanks for letting me know so quickly :) I'll bump a new version as a patch.

**Comment by DenisCarriere** [comment]
Now published under `v1.29.1`

**Pull request merged**
