### PR TITLE
added US Census Geocoder as a provider

### PR DESCRIPTION
**Pull request by star-is-here**
Saw this as an enhancement issue. Added basic forward and reverse geocode for US Census geocoder.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@star-is-here Everything looks great, however can you submit new commits with the appropriate fixes and I'll be able to merge this PR afterwards.

1. Fix the few PEP8 syntax issues.

2. Add `uscensus` test cases to [`tests/test_geocoder.py`](https://github.com/DenisCarriere/geocoder/blob/master/tests/test_geocoder.py)

**Travis CI Build fail**
https://travis-ci.org/DenisCarriere/geocoder/jobs/180522081
```
=================================== FAILURES ===================================
__________________________ PEP8-check(ignoring E501) ___________________________
/home/travis/build/DenisCarriere/geocoder/geocoder/api.py:528:1: E302 expected 2 blank lines, found 1
def uscensus(location, **kwargs):
^
__________________________ PEP8-check(ignoring E501) ___________________________
/home/travis/build/DenisCarriere/geocoder/geocoder/uscensus.py:126:14: W292 no newline at end of file
    g.debug()
             ^
__________________________ PEP8-check(ignoring E501) ___________________________
/home/travis/build/DenisCarriere/geocoder/geocoder/uscensus_reverse.py:99:14: W292 no newline at end of file
    g.debug()
             ^
```

**Comment by star-is-here** [comment]
@DenisCarriere Thanks for the fast reply!. I think with the latest commit I've added all the changes.

**Comment by DenisCarriere** [comment]
@star-is-here Looks great! Thanks for your contributions 👍

**Comment by DenisCarriere** [comment]
Bumped the version of the Geocoder library to `1.19.0`, you're feature is now available from `pip install geocoder`.

**Pull request merged**
